<?php

namespace Database\Seeders;

use App\Models\Term;
use Illuminate\Database\Seeder;

class TermSeeder extends Seeder
{
    private array $terms = [
        // Easy phrases
        ['value' => 'walk the dog', 'difficulty' => 'easy', 'category' => 'activities'],
        ['value' => 'pizza party', 'difficulty' => 'easy', 'category' => 'food'],
        ['value' => 'cat nap', 'difficulty' => 'easy', 'category' => 'animals'],
        ['value' => 'beach day', 'difficulty' => 'easy', 'category' => 'activities'],
        ['value' => 'dog house', 'difficulty' => 'easy', 'category' => 'animals'],
        ['value' => 'hot chocolate', 'difficulty' => 'easy', 'category' => 'food'],
        ['value' => 'morning coffee', 'difficulty' => 'easy', 'category' => 'food'],
        ['value' => 'puppy love', 'difficulty' => 'easy', 'category' => 'animals'],
        ['value' => 'piggy bank', 'difficulty' => 'easy', 'category' => 'objects'],
        ['value' => 'flower pot', 'difficulty' => 'easy', 'category' => 'nature'],
        ['value' => 'bird cage', 'difficulty' => 'easy', 'category' => 'animals'],
        ['value' => 'road trip', 'difficulty' => 'easy', 'category' => 'activities'],
        ['value' => 'love bird', 'difficulty' => 'easy', 'category' => 'animals'],
        ['value' => 'honey bee', 'difficulty' => 'easy', 'category' => 'animals'],
        ['value' => 'paper plane', 'difficulty' => 'easy', 'category' => 'objects'],
        ['value' => 'polar bear', 'difficulty' => 'easy', 'category' => 'animals'],
        ['value' => 'rainbow fish', 'difficulty' => 'easy', 'category' => 'animals'],
        ['value' => 'sun burn', 'difficulty' => 'easy', 'category' => 'nature'],
        ['value' => 'snowball fight', 'difficulty' => 'easy', 'category' => 'activities'],
        ['value' => 'money tree', 'difficulty' => 'easy', 'category' => 'nature'],
        ['value' => 'rose garden', 'difficulty' => 'easy', 'category' => 'nature'],
        ['value' => 'lemon tree', 'difficulty' => 'easy', 'category' => 'nature'],
        ['value' => 'thunder storm', 'difficulty' => 'easy', 'category' => 'nature'],
        ['value' => 'star fish', 'difficulty' => 'easy', 'category' => 'animals'],
        ['value' => 'book worm', 'difficulty' => 'easy', 'category' => 'misc'],
        // Medium phrases
        ['value' => 'midnight snack', 'difficulty' => 'medium', 'category' => 'food'],
        ['value' => 'rain dance', 'difficulty' => 'medium', 'category' => 'activities'],
        ['value' => 'night owl', 'difficulty' => 'medium', 'category' => 'animals'],
        ['value' => 'early bird', 'difficulty' => 'medium', 'category' => 'animals'],
        ['value' => 'spring cleaning', 'difficulty' => 'medium', 'category' => 'activities'],
        ['value' => 'time bomb', 'difficulty' => 'medium', 'category' => 'objects'],
        ['value' => 'treasure hunt', 'difficulty' => 'medium', 'category' => 'activities'],
        ['value' => 'sunset cruise', 'difficulty' => 'medium', 'category' => 'activities'],
        ['value' => 'moon walk', 'difficulty' => 'medium', 'category' => 'activities'],
        ['value' => 'fish tank', 'difficulty' => 'medium', 'category' => 'objects'],
        ['value' => 'ghost town', 'difficulty' => 'medium', 'category' => 'misc'],
        ['value' => 'tidal wave', 'difficulty' => 'medium', 'category' => 'nature'],
        ['value' => 'wild fire', 'difficulty' => 'medium', 'category' => 'nature'],
        ['value' => 'wolf pack', 'difficulty' => 'medium', 'category' => 'animals'],
        ['value' => 'snake charmer', 'difficulty' => 'medium', 'category' => 'misc'],
        ['value' => 'lion king', 'difficulty' => 'medium', 'category' => 'animals'],
        ['value' => 'monkey bars', 'difficulty' => 'medium', 'category' => 'objects'],
        ['value' => 'spider web', 'difficulty' => 'medium', 'category' => 'animals'],
        ['value' => 'turtle neck', 'difficulty' => 'medium', 'category' => 'objects'],
        ['value' => 'sweet tooth', 'difficulty' => 'medium', 'category' => 'food'],
        ['value' => 'belly flop', 'difficulty' => 'medium', 'category' => 'activities'],
        ['value' => 'broken heart', 'difficulty' => 'medium', 'category' => 'misc'],
        ['value' => 'green thumb', 'difficulty' => 'medium', 'category' => 'nature'],
        ['value' => 'pot of gold', 'difficulty' => 'medium', 'category' => 'misc'],
        ['value' => 'shooting star', 'difficulty' => 'medium', 'category' => 'nature'],
        ['value' => 'rock band', 'difficulty' => 'medium', 'category' => 'music'],
        ['value' => 'snail mail', 'difficulty' => 'medium', 'category' => 'misc'],
        ['value' => 'cold shoulder', 'difficulty' => 'medium', 'category' => 'misc'],
        ['value' => 'road rage', 'difficulty' => 'medium', 'category' => 'activities'],
        ['value' => 'chicken dance', 'difficulty' => 'medium', 'category' => 'activities'],
        ['value' => 'turkey leg', 'difficulty' => 'medium', 'category' => 'food'],
        ['value' => 'penguin parade', 'difficulty' => 'medium', 'category' => 'animals'],
        ['value' => 'shark attack', 'difficulty' => 'medium', 'category' => 'animals'],
        ['value' => 'fire breathing dragon', 'difficulty' => 'medium', 'category' => 'misc'],
        ['value' => 'running late', 'difficulty' => 'medium', 'category' => 'activities'],
        ['value' => 'cat and mouse', 'difficulty' => 'medium', 'category' => 'animals'],
        ['value' => 'fish out of water', 'difficulty' => 'medium', 'category' => 'animals'],
        ['value' => 'bull in a china shop', 'difficulty' => 'medium', 'category' => 'misc'],
        ['value' => 'wolf in sheeps clothing', 'difficulty' => 'medium', 'category' => 'animals'],
        // Hard phrases
        ['value' => 'laughing stock', 'difficulty' => 'hard', 'category' => 'misc'],
        ['value' => 'nightmare', 'difficulty' => 'hard', 'category' => 'misc'],
        ['value' => 'happy hour', 'difficulty' => 'hard', 'category' => 'activities'],
        ['value' => 'eye candy', 'difficulty' => 'hard', 'category' => 'misc'],
        ['value' => 'heart attack', 'difficulty' => 'hard', 'category' => 'misc'],
        ['value' => 'monkey business', 'difficulty' => 'hard', 'category' => 'misc'],
        ['value' => 'couch potato', 'difficulty' => 'hard', 'category' => 'misc'],
        ['value' => 'cry wolf', 'difficulty' => 'hard', 'category' => 'misc'],
        ['value' => 'bite the bullet', 'difficulty' => 'hard', 'category' => 'misc'],
        ['value' => 'kick the bucket', 'difficulty' => 'hard', 'category' => 'misc'],
        ['value' => 'spill the beans', 'difficulty' => 'hard', 'category' => 'misc'],
        ['value' => 'hit the sack', 'difficulty' => 'hard', 'category' => 'misc'],
        ['value' => 'barking up the wrong tree', 'difficulty' => 'hard', 'category' => 'misc'],
        ['value' => 'let the cat out of the bag', 'difficulty' => 'hard', 'category' => 'misc'],
        ['value' => 'sleep like a log', 'difficulty' => 'hard', 'category' => 'misc'],
        ['value' => 'raining cats and dogs', 'difficulty' => 'hard', 'category' => 'nature'],
        ['value' => 'kill two birds one stone', 'difficulty' => 'hard', 'category' => 'misc'],
        ['value' => 'once in a blue moon', 'difficulty' => 'hard', 'category' => 'misc'],
        ['value' => 'beating a dead horse', 'difficulty' => 'hard', 'category' => 'misc'],
        ['value' => 'elephant in the room', 'difficulty' => 'hard', 'category' => 'misc'],
        ['value' => 'frog in a boiling pot', 'difficulty' => 'hard', 'category' => 'misc'],
        ['value' => 'chasing your tail', 'difficulty' => 'hard', 'category' => 'misc'],
        ['value' => 'hold your horses', 'difficulty' => 'hard', 'category' => 'misc'],
        ['value' => 'penguin in the desert', 'difficulty' => 'hard', 'category' => 'animals'],
        ['value' => 'dinosaur driving a car', 'difficulty' => 'hard', 'category' => 'misc'],
        ['value' => 'astronaut eating pizza', 'difficulty' => 'hard', 'category' => 'misc'],
        ['value' => 'robot playing guitar', 'difficulty' => 'hard', 'category' => 'misc'],
        ['value' => 'cat riding a rocket', 'difficulty' => 'hard', 'category' => 'animals'],
        ['value' => 'witch flying over city', 'difficulty' => 'hard', 'category' => 'misc'],
        ['value' => 'knight fighting dragon', 'difficulty' => 'hard', 'category' => 'misc'],
        ['value' => 'mermaid eating sushi', 'difficulty' => 'hard', 'category' => 'misc'],
        ['value' => 'bee stealing honey', 'difficulty' => 'hard', 'category' => 'animals'],
        ['value' => 'dog chasing its tail', 'difficulty' => 'hard', 'category' => 'animals'],
        ['value' => 'sun setting over ocean', 'difficulty' => 'hard', 'category' => 'nature'],
        ['value' => 'cow jumping over moon', 'difficulty' => 'hard', 'category' => 'misc'],
        ['value' => 'bear catching salmon', 'difficulty' => 'hard', 'category' => 'animals'],
    ];

    public function run(): void
    {
        foreach ($this->terms as $term) {
            Term::create($term);
        }
    }
}
